=== RudyChin/pmctrack/src/gui/backend/xml_definitions/events.dtd
<!ELEMENT pmcs_and_events (pmcs?,events)>

<!ELEMENT pmcs (pmc*)>
<!ELEMENT pmc (pmc_name,pmc_type,pmc_number)>
<!ELEMENT pmc_name (#PCDATA)>
<!ELEMENT pmc_type (#PCDATA)>
<!ELEMENT pmc_number (#PCDATA)>

<!ELEMENT events (event+)>
<!ELEMENT event (name,descp?,code,flags?,subevents?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT descp (#PCDATA)>
<!ELEMENT flags (flag*)>
<!ELEMENT subevents (subevent+)>

<!ELEMENT subevent (subevt_name,subevt_descp?,flags)>
<!ELEMENT subevt_name (#PCDATA)>
<!ELEMENT subevt_descp (#PCDATA)>

<!ELEMENT flag (flag_name,flag_value)>
<!ELEMENT flag_name (#PCDATA)>
<!ELEMENT flag_value (#PCDATA)>

=== RudyChin/pmctrack/src/gui/backend/xml_definitions/armv8.cortex_a57.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pmcs_and_events SYSTEM "events.dtd">
<!-- xml defining fixed pmcs and hardware events to monitor for this model -->
<!-- This xml has been generated automatically from a csv definition file -->
<pmcs_and_events>
<pmcs>
	<pmc>
		<pmc_name>cycles_allmodes</pmc_name>
		<pmc_type>fixed</pmc_type>
		<pmc_number>0</pmc_number>
	</pmc>

</pmcs>
<events>
	<event>
		<name>instr</name>
		<code>0x8</code>
	</event>
	<event>
		<name>ase_spec</name>
		<code>0x74</code>
	</event>
	<event>
		<name>l2_cache_refills</name>
		<code>0x17</code>
	</event>
	<event>
		<name>llc_accesses</name>
		<code>0x16</code>
	</event>
	<event>
		<name>instr_spec_executed</name>
		<code>0x1b</code>
	</event>
	<event>
		<name>l1_instr_refills</name>
		<code>0x1</code>
	</event>
	<event>
		<name>data_read_retired</name>
		<code>0x66</code>
	</event>
	<event>
		<name>l1_data_refills</name>
		<code>0x03</code>
	</event>
	<event>
		<name>data_cache_eviction</name>
		<code>0x15</code>
	</event>
	<event>
		<name>bus_read_accesses</name>
		<code>0x60</code>
	</event>
	<event>
		<name>dtlb_misses</name>
		<code>0x5</code>
	</event>
	<event>
		<name>potentially_predicted_branches</name>
		<code>0x12</code>
	</event>
	<event>
		<name>ldst_spec</name>
		<code>0x72</code>
	</event>
	<event>
		<name>itlb_misses</name>
		<code>0x2</code>
	</event>
	<event>
		<name>llc_misses</name>
		<code>0x17</code>
	</event>
	<event>
		<name>dp_spec</name>
		<code>0x73</code>
	</event>
	<event>
		<name>data_write_retired</name>
		<code>0x67</code>
	</event>
	<event>
		<name>mispred_branches</name>
		<code>0x10</code>
	</event>
	<event>
		<name>bus_write_accesses</name>
		<code>0x61</code>
	</event>
	<event>
		<name>st_spec</name>
		<code>0x71</code>
	</event>
	<event>
		<name>ld_spec</name>
		<code>0x70</code>
	</event>
	<event>
		<name>bus_accesses</name>
		<code>0x19</code>
	</event>
	<event>
		<name>inmediate_branches_retired</name>
		<code>0x0d</code>
	</event>
	<event>
		<name>l2_cache_accesses</name>
		<code>0x16</code>
	</event>
	<event>
		<name>instr_cache_access</name>
		<code>0x14</code>
	</event>
	<event>
		<name>vfp_spec</name>
		<code>0x75</code>
	</event>
	<event>
		<name>instr_arch_executed</name>
		<code>0x8</code>
	</event>
	<event>
		<name>br_inmed_spec</name>
		<code>0x78</code>
	</event>
	<event>
		<name>l2_cache_writebacks</name>
		<code>0x18</code>
	</event>
	<event>
		<name>br_indirect_spec</name>
		<code>0x79</code>
	</event>
	<event>
		<name>l1_data_accesses</name>
		<code>0x04</code>
	</event>
	<event>
		<name>cycles</name>
		<code>0x11</code>
	</event>
	<event>
		<name>data_mem_access</name>
		<code>0x13</code>
	</event>

</events>
</pmcs_and_events>
