=== RudyChin/pmctrack/src/gui/backend/xml_definitions/layout.dtd
<!ELEMENT layout (field*)>
<!ATTLIST layout 
vendor (intel|amd|arm|undefined) #IMPLIED
family CDATA #IMPLIED
version CDATA #IMPLIED>

<!ELEMENT field (name,nbits,default)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nbits (#PCDATA)>
<!ELEMENT default (#PCDATA)>

=== RudyChin/pmctrack/src/gui/backend/xml_definitions/arm_layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE layout SYSTEM "layout.dtd">
<layout vendor="arm"  version="0.0">
	<!-- number of bits for each configurable field -->

  <field>
    <name>os</name>
    <nbits>1</nbits>
    <default>0</default>
  </field>			
  <field>
    <name>usr</name>
    <nbits>1</nbits>
    <default>1</default>
  </field>	
  <field>
    <name>ebs</name>
    <nbits>32</nbits>
    <default>0</default>
  </field>	
  
</layout>

=== RudyChin/pmctrack/src/gui/backend/xml_definitions/intel_layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE layout SYSTEM "layout.dtd">
<layout vendor="intel" family="6">
	<!-- number of bits for each configurable field -->
		
  <field>
    <name>cmask</name>
    <nbits>8</nbits>
    <default>0</default>
  </field>
  <field>
    <name>inv</name>
    <nbits>1</nbits>
    <default>0</default>
  </field>
  <field>
    <name>os</name>
    <nbits>1</nbits>
    <default>0</default>
  </field>			
  <field>
    <name>usr</name>
    <nbits>1</nbits>
    <default>1</default>
  </field>	
  <field>
    <name>edge</name>
    <nbits>1</nbits>
    <default>1</default>
  </field>	
  <field>
    <name>umask</name>
    <nbits>8</nbits>
    <default>0</default>
  </field>	
		
</layout>
